name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishPackage
    displayName: 🚀 Publish dwarf-debugging
    type: boolean
    default: false

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: dwarf-debugging
        ghCreateTag: false
        timeoutInMinutes: 120
        buildSteps:
          - script: npm ci
            displayName: Install dependencies

          - script: npm run build-native-ext-image
            displayName: Build CXX extension

          - script: npm run copy-out-native-ext
            displayName: Copy out extension

          - script: npm run test
            displayName: Test

        testPlatforms: []

        # Build container does not run on Windows
        skipAPIScan: true

        publishPackage: ${{ parameters.publishPackage }}
